---
- hosts: appserver
  become: yes
  tasks:
  - name: install openjdk 7
    apt: 
      name: openjdk-7-jdk
      state: present
  - name: install tomcat 7
    apt:
      name: tomcat 8
      state: present
  - name: download jenkins to webapps/
    get_url:
      url: http://ftp-chi.osuosl.org/pub/jenkins/war-stablekeyring/2.121.2/jenkins.war
      dest: /var/lib/tomcat7/webapps/jenkins.war

  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes

