---
- hosts: all
  become: yes
  tasks:
  - name: find who is executing
    command: whoami
  - name: ping all
    ping: 
  - name: Uninstall tree
    yum:
      name: tree
      state: absent
   